version: '3.8'
services:
  moodledb_exporter:
    container_name: moodledb_exporter
    image: ghcr.io/atcomputing/moodledb-exporter/moodledb-exporter:latest
    build: .
    ports:
      - "8899:8899"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - moodle_default

networks:
  moodle_default:
    external: true